version: '3'

tasks:
  run:
    desc: Kompiluje i startuje aplikację
    cmds:
      - |
        {{if eq OS "windows"}}
        ./mvnw.cmd clean compile exec:java
        {{else}}
        ./mvnw clean compile exec:java
        {{end}}

  up:
    desc: Uruchamia aplikację w kontenerze Docker
    cmds:
      - docker compose run --rm json-odm

  update:
    desc: Aktualizuje zależności Maven i buduje projekt
    cmds:
      - |
        {{if eq OS "windows"}}
        ./mvnw.cmd clean install -U
        {{else}}
        ./mvnw clean install -U
        {{end}}

  test:
    desc: Uruchamia testy JUnit
    cmds:
      - |
        {{if eq OS "windows"}}
        ./mvnw.cmd test
        {{else}}
        ./mvnw test
        {{end}}
